spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:rewardsdb
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: none
#   properties.hibernate.format_sql: true
#logging:
#   level:
#     org:
#       hibernate.SQL: DEBUG
#       hibernate.type: TRACE
